version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.go
      # args:
      #   - GIT_USERNAME=${GIT_USERNAME}
      #   - GIT_TOKEN=${GIT_TOKEN}
    image: 2359634711/story_api:latest
    volumes:
      - ./tmp/log:/app/tmp/log
    ports:
      - 18006:18005
    restart: always
    depends_on:
      - db
    # networks:
    #   - mynetwork
  node:
    image: 2359634711/story_node:latest
    container_name: story_node
    build:
      context: .
      dockerfile: Dockerfile.node
    restart: unless-stopped
    volumes:
      - ~/log/server:/crawler/server/tmp
    ports:
      - "3001:3000"
    # networks:
    #   - mynetwork
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: 2359634711/story_db:latest
    container_name: story_db
    volumes:
      - ~/opt/data:/var/lib/mysql
      - ~/opt/log:/var/log/mysql
      - ~/opt/mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3307:3306"
    # networks:
    #   - mynetwork
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
      - ./certs:/etc/ssl/private
    depends_on:
      - node
      - api
    # networks:
    #   - mynetwork
# networks:
#   mynetwork:

volumes:
  certs:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local
