FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD 123456

# Copy custom configuration file
COPY ./apps/db/conf/my.cnf /etc/mysql/conf.d/my.cnf

# Copy initialization script
COPY ./apps/db/init.sql /docker-entrypoint-initdb.d/init.sql

# Expose port 3306
EXPOSE 3306