// Code generated by goctl. DO NOT EDIT.

export interface Request {
}
export interface RequestParams {
}

export interface Response {
	message: string
}

export interface StoriesRequest {
}
export interface StoriesRequestParams {
}

export interface Story {
	id?: number
	name?: string
	description?: string
	data?: string
	create_time?: string
	update_time?: string
	audio_link?: string
	audio_Url?: string
	status?: number
}

export interface CosCredentials {
	TmpSecretId?: string
	TmpSecretKey?: string
	Token?: string
}

export interface StoryRequest {
	story?: Story
	random?: boolean
}

export interface StoryDetailRequest {
}
export interface StoryDetailRequestParams {
	id: number
	random: boolean
}

export interface StoryResponse {
	message: string
	data: Story
}

export interface StoriesResponse {
	message: string
	data: Array<Story>
}

export interface CosCredentialsResponse {
	message: string
	data: CosCredentials
}

export interface CosCredentialsRequest {
}
export interface CosCredentialsRequestParams {
	key: string
}

export interface TextToSpeechResponse {
	data: Blob
}

export interface TextToSpeechRequest {
	text: string
}

