// Code generated by goctl. DO NOT EDIT.

export interface Request {
}
export interface RequestParams {
}

export interface Response {
	message: string
}

export interface TasksRequest {
}
export interface TasksRequestParams {
}

export interface Task {
	id?: number
	name?: string
	description?: string
	data?: string
	create_time?: string
	update_time?: string
	ori_img_key?: string
	img_url?: string
	status?: number
}

export interface User {
	id?: number
	username?: string
	password?: string
	create_time?: string
	update_time?: string
	jwt?: string
	status?: number
}

export interface Login {
}
export interface LoginParams {
	username: string
	password: string
}

export interface CosCredentials {
	TmpSecretId?: string
	TmpSecretKey?: string
	Token?: string
}

export interface TaskRequest {
	task?: Task
	random?: boolean
}

export interface TaskDetailRequest {
}
export interface TaskDetailRequestParams {
	id: number
	random: boolean
}

export interface TaskResponse {
	message: string
	data: Task
}

export interface TasksResponse {
	message: string
	data: Array<Task>
}

export interface UserResponse {
	message?: string
	status?: number // 0 注册/登录成功 1 账号重复/登录失败
	user?: User
}

export interface CosCredentialsResponse {
	message: string
	data: CosCredentials
}

export interface CosCredentialsRequest {
}
export interface CosCredentialsRequestParams {
	key: string
}

export interface TextToSpeechResponse {
	data: Blob
}

export interface TextToSpeechRequest {
	text: string
}

