// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHistory = " history"

// History mapped from table < history>
type History struct {
}

// TableName History's table name
func (*History) TableName() string {
	return TableNameHistory
}
