// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = " tasks"

// Task mapped from table < tasks>
type Task struct {
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
