// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStory = "stories"

// Story mapped from table <stories>
type Story struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null;comment:故事名称" json:"name"`
	Description string    `gorm:"column:description;not null;comment:描述" json:"description"`
	Channel     string    `gorm:"column:channel;not null;comment:渠道" json:"channel"`
	AudioLink   string    `gorm:"column:audio_link;comment:音频的链接" json:"audio_link"`
	Data        string    `gorm:"column:data;comment:json详细信息，封面、内容等" json:"data"`
	Source      int32     `gorm:"column:source;not null;comment:来源" json:"source"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(6)" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(6)" json:"update_time"`
	Status      int32     `gorm:"column:status;not null;comment:1=待审核, 2=审核通过, 3=审核失败" json:"status"`
}

// TableName Story's table name
func (*Story) TableName() string {
	return TableNameStory
}
