// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null;comment:task名称" json:"name"`                         // task名称
	Description  string    `gorm:"column:description;not null;comment:task描述" json:"description"`           // task描述
	OriImgKey    string    `gorm:"column:ori_img_key;comment:original image" json:"ori_img_key"`            // original image
	LatestImgKey string    `gorm:"column:latest_img_key;comment:masked matest image" json:"latest_img_key"` // masked matest image
	Data         string    `gorm:"column:data;comment:json详细信息" json:"data"`                                // json详细信息
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(6)" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(6)" json:"update_time"`
	Status       int32     `gorm:"column:status;not null;comment:1=待审核, 2=审核通过, 3=审核失败" json:"status"` // 1=待审核, 2=审核通过, 3=审核失败
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
