// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username   string    `gorm:"column:username;not null;comment:user" json:"username"`         // user
	Password   string    `gorm:"column:password;not null;comment:md5_password" json:"password"` // md5_password
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(6)" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(6)" json:"update_time"`
	Status     int32     `gorm:"column:status;not null;comment:1=待审核, 2=审核通过, 3=审核失败" json:"status"` // 1=待审核, 2=审核通过, 3=审核失败
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
