// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=[you,me]"` // parameters are auto validated
}

type Response struct {
	Message string `json:"message"`
}

type TasksRequest struct {
	Keyword string `query:"keyword"` // parameters are auto validated
}

type Task struct {
	Id          int64  `json:"id,optional"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Data        string `json:"data,optional"`
	CreateTime  string `json:"create_time,optional"`
	UpdateTime  string `json:"update_time,optional"`
	OriImgKey   string `json:"ori_img_key,optional"`
	ImgUrl      string `json:"img_url,optional"`
	Status      int32  `json:"status,optional"`
}

type CosCredentials struct {
	TmpSecretID  string `json:"TmpSecretId,omitempty"`
	TmpSecretKey string `json:"TmpSecretKey,omitempty"`
	SessionToken string `json:"Token,omitempty"`
}

type TaskRequest struct {
	Task   Task `json:"task,optional"`
	Random bool `json:"random,optional"`
}

type TaskDetailRequest struct {
	Id     int64 `form:"id,optional"`
	Random bool  `form:"random,optional"`
}

type TaskResponse struct {
	Message string `json:"message"`
	Data    Task   `json:"data"`
}

type TasksResponse struct {
	Message string `json:"message"`
	Data    []Task `json:"data"`
}

type CosCredentialsResponse struct {
	Message string         `json:"message"`
	Data    CosCredentials `json:"data"`
}

type CosCredentialsRequest struct {
	Key string `form:"key"`
}

type TextToSpeechResponse struct {
	Data []byte `json:"data"`
}

type TextToSpeechRequest struct {
	Text string `json:"text"`
}
