// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"story-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/from/:name",
				Handler: GreetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/stories",
				Handler: StoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/stories",
				Handler: CreateStoryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/stories",
				Handler: DeleteStoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/stories",
				Handler: UpdateStoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/story",
				Handler: StoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/cos_credentials",
				Handler: CosCredentialsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/text2speech",
				Handler: TextToSpeechHandler(serverCtx),
			},
		},
	)
}
